title: Run Docker container
description : |
  Run previously tagged docker container:
 
  * Container must be started from image "webserver:v0.1"
  * Container must be exposed to the port 8080 (default 80)
  * Container must have attached volume "li9" to the "/test" directory
  * Directory "/test" should have an empty file "funky"

explanation: |
  A participant should do following:
  * Run previously tagged docker container "webserver:v0.1" with exposed port 80880 and attached volume "li9" to the "/test" directory
  * When container started, participant should login to container and create there an empty file "/test/funky"