---

  - name:
    hosts: "vm"
    gather_facts: False
    become_method: su
    become_user: root
    vars_files:
    - group_vars/all.yml
    tasks:
      - name: Ensure SSH warning banner is configured
        copy:
          dest: /etc/issue.net
          src: "files/issue.net"

      - name: add lines
        lineinfile:
          dest: /etc/ssh/sshd_config
          line: 'Banner /etc/issue.net'

      - name: restart sshd
        service:
          name: sshd
          state: restarted

      - name: list of commands for prepare tests
        file:
          state: directory
          path: /data
          owner: root
          group: root

#        command: "mkdir -p /data"
      - file:
          path: /data/removeme
          attributes: "+i"
          state: touch
          owner: root
          group: root
  
#      - command: "touch /data/removeme"
#      - command: "chattr +i /data/removeme"

      - name: send an email with results
        mail:
          subject: "Test results"
          to: "{{ adminemailnotifications }}"
          from: Li9 Demo <do-not-reply@demo.li9.com>
          body: 'System has been successfully provisioned.'
