- name:
  hosts: "{{ vmhostip }}"
  gather_facts: false

  vars:
    tasks_base_dir: "li9_exam_system/{{ testname }}/"
    exam_name: "Linux system administration exam"

  tasks:

      - name: Get tasks
        set_fact:
          exam_tasks: "{{ lookup('listtasks', tasks_base_dir) }}"

      - name: Save the tasks details for later using
        set_stats:
          data:
            exam_tasks: "{{ exam_tasks }}"


      - name: Debug selected tasks
        debug: var=exam_tasks


      - name: Doing common bootstrapping
        include_tasks: "{{ item }}"
        loop:
          - li9_exam_system/{{ testname }}/common_bootstrap.yml


      - name: Execute selected tasks specific ansible-tasks
        include_tasks: "{{ exam_tasks.rootpath }}/{{ item.value.selected_task_path }}/pre_config.yml"
        with_dict: "{{ exam_tasks.topics }}"


      - name: Emailing tasks
        include_tasks: "{{ item }}"
        loop:
          - included_tasks/send_tasks.yml


      - name: Call wait Job
        include_tasks: "included_tasks/tower_client.yml"
        vars:
          job_template_name: "{{ job_templates.waittime.name }}"
          tower_action: "job_launch"
          tower_job_url: "{{ job_templates.waittime.endpoint }}"
          job_extra_vars:
            extra_vars:
              participant_id: "{{ participant_id | default('') }}"
              participant_details: "{{ participant_details | default('') }}"
              participant_email: "{{ participant_email | default(useremailnotifications) }}"
              initiator_email: "{{ initiator_email }}"
              useremailnotifications: "{{ useremailnotifications }}"
              testname: "{{ testname }}"
              stack_name: "{{ stack_name }}"
              student_name: "{{ student_name }}"
              exam_length_seconds: "{{ exam_length_seconds }}"

