---
  - name:
#    hosts: "{{ my_stack.ansible_facts.cloudformation[stack_name].stack_outputs.TestServerIp }}"
    hosts: "{{ vmhostip }}"
#    connection: local
#    hosts: all
    gather_facts: true
#    become_method: su
#    become_user: root
#    vars_files:
#    - group_vars/all.yml
    tasks:
      - debug:
          msg: "our inventnmame {{ playbookvminventoryname }} and creds {{ playbookvmcredentialsname }}"

      - name: Ensure SSH warning banner is configured
        copy:
          dest: "/etc/issue.net"
          src: "files/issue.net"

      - name: add lines
        lineinfile:
         dest: /etc/ssh/sshd_config
         line: 'Banner /etc/issue.net'

      - name: restart sshd
        service:
          name: sshd
          state: restarted

      - name: list of commands for prepare tests
        file:
          state: directory
          path: /data
          owner: root
          group: root

      - name: create file with chattr +i
        file:
          path: /data/removeme
          attributes: "+i"
          state: touch
          owner: root
          group: root
  
      - name: enable additional repo for docker
        shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

      - name: Install a list of packages
        yum:
          name: "{{ packages }}"
        vars:
          packages:
             - yum-utils
             - device-mapper-persistent-data
             - lvm2
             - docker-ce
             - docker-ce-cli
             - containerd.io

      - name: restart sshd
        service:
          name: docker
          state: restarted

      - name: send an email with results
        mail: 
          subject: "Test results"
          to: "{{ adminemailnotifications }}"
          from: Li9 Demo <do-not-reply@demo.li9.com>
          body: 'System has been successfully provisioned.'
