---
  - name:
    hosts: "{{ vmhostip }}"
    gather_facts: true
    tasks:

      - debug:
          msg: "our inventnmame {{ playbookvminventoryname }}"
        when: testname == "linux"

      - name: Ensure SSH warning banner is configured
        copy:
          dest: "/etc/issue.net"
          src: "files/issue.net"
        when: testname == "linux"

      - name: add lines
        lineinfile:
         dest: /etc/ssh/sshd_config
         line: 'Banner /etc/issue.net'
        when: testname == "linux"

      - name: restart sshd
        service:
          name: sshd
          state: restarted
        when: testname == "linux"

      - name: list of commands for prepare tests
        file:
          state: directory
          path: /data
          owner: root
          group: root
        when: testname == "linux"

      - name: creating /data/removeme
        file:
          state: touch
          path: /data/removeme
          state: touch
          mode: "u+rwx,g+rwx,o+rwx"
        when: testname == "linux"

      - name: create file with chattr +i
        shell: chattr +i /data/removeme
        when: testname == "linux"
  
      - name: enable additional repo for docker
        shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
        when: testname == "linux"

      - name: Install a list of packages
        yum:
          name: "{{ packages }}"
        vars:
          packages:
             - yum-utils
             - device-mapper-persistent-data
             - lvm2
#             - docker-ce
#             - docker-ce-cli
#             - containerd.io
        when: testname == "linux"

      - name: restart sshd
        service:
          name: docker
          state: restarted
        when: testname == "linux"

#      - name: send an email with results
#        mail: 
#          subject: "Postconfigurations has been done"
#          to: "{{ adminemailnotifications }}"
#          from: Li9 Exam <do-not-reply@li9.com>
#          body: 'Test-VM is redy for exam.'

      - name: press to link for exam start
        mail:
          subject: "youre exam is ready"
          to: "{{ useremailnotifications }}"
#          from: Li9 Exam <do-not-reply@li9.com>
          from: "{{ adminemailnotifications }}"
          subtype: html
          body: "{{ lookup('template', 'templates/mail.html.j2') }}"
        when: testname == "linux"

#### install ang configure asciinema recorder

      - name: Install epel packag
        yum:
          name: epel-release
          state: latest
        when: testname == "linux"

      - name: Install a asciinema package
        yum:
          name: asciinema
          state: latest
        when: testname == "linux"

      - name: copy main config file
        copy:
          dest: /root/.config/asciinema/config
          src: "templates/asciinema.config"
        when: testname == "linux"

      - name: add lines into bash_profile
        lineinfile:
         dest: /root/.bash_profile
         line: 'asciinema rec -y -q -t "emailofuser@com.com"'
        when: testname == "linux"
