- name:
  hosts: "{{ vmhostip }}"
  gather_facts: false

  vars:
    tasks_base_dir: "li9_exam_system/{{ testname }}/"
    exam_name: "Linux system administration exam"

  tasks:

  - name: Run direct tasks
    block:

      - name: Get tasks
        set_fact:
          exam_tasks: "{{ lookup('listtasks', tasks_base_dir) }}"

      - name: Save the tasks details for later using
        set_stats:
          data:
            exam_tasks: "{{ exam_tasks }}"


      - name: Debug selected tasks
        debug: var=exam_tasks


      - name: Doing common bootstrapping
        include_tasks: "{{ item }}"
        loop:
          - li9_exam_system/common_bootstrap.yml
          - li9_exam_system/{{ testname }}/common_bootstrap.yml
        vars:
          asciinema_recid: "{% if participant_id != '' -%}{{ participant_email }}-{{ participant_id }}{%- else -%}{{ participant_email }}{%- endif %}"
          username: "{{ student_name }}"


      - name: Execute selected tasks specific ansible-tasks
        include_tasks: "{{ exam_tasks.rootpath }}/{{ item.value.selected_task_path }}/pre_config.yml"
        with_dict: "{{ exam_tasks.topics }}"

# It fails by an unkown reason disabling for a while
#      - name: Calling checking ssh credentials
#        include_tasks: "included_tasks/check_ssh_creds.yml"


      - name: Send email to the developer
        include_tasks: "included_tasks/tower_client.yml"
        vars:
          send_to: "{{ developers_emails }}"
          mail_subject: "Li9ExamSystem SSH password check did not pass"
          mail_body: |
            Dear Developer,

            The deployed host did not pass "ssh password check".
            Details:
              participant_id: "{{ participant_id | default('') }}"
              participant_details: "{{ participant_details | default('') }}"
              participant_email: "{{ participant_email | default(useremailnotifications) }}"
              initiator_email: "{{ initiator_email }}"
              useremailnotifications: "{{ useremailnotifications }}"
              testname: "{{ testname }}"
              stack_name: "{{ stack_name }}"
              student_name: "{{ student_name }}"
              exam_length_seconds: "{{ exam_length_seconds }}"
              vmhostip: "{{ vmhostip }}"

            Sincerely,
            Your system

          body_content_format: "plain"
        when:
          # set this as true by default but actually it should be checked on false
          # so far it is a workaround
          - not check_sshpass_passed | default(true)


      - name: Emailing tasks
        include_tasks: "{{ item }}"
        loop:
          - included_tasks/send_tasks.yml
        vars:
          examtime: "{{ exam_length_seconds | int }}"


      - name: Call wait Job
        include_tasks: "included_tasks/tower_client.yml"
        vars:
          job_template_name: "{{ job_templates.waittime.name }}"
          tower_action: "job_launch"
          tower_job_url: "{{ job_templates.waittime.endpoint }}"
          job_extra_vars:
            extra_vars:
              participant_id: "{{ participant_id | default('') }}"
              participant_details: "{{ participant_details | default('') }}"
              participant_email: "{{ participant_email | default(useremailnotifications) }}"
              initiator_email: "{{ initiator_email }}"
              useremailnotifications: "{{ useremailnotifications }}"
              testname: "{{ testname }}"
              stack_name: "{{ stack_name }}"
              student_name: "{{ student_name }}"
              exam_length_seconds: "{{ exam_length_seconds }}"
              vmhostip: "{{ vmhostip }}"
              exam_tasks: "{{ exam_tasks }}"
    rescue:

      - name: Something went wrong and we remove allocated in AWS resources
        include_tasks: "included_tasks/remove_aws_stack.yml"
        vars:
          send_notify_email: true
          bad_situation: true
          mail_subject: "Postconfig failed, check logs"
          mail_message: "The postconfig playbook failed."

