---
  - name:
    hosts: "{{ vmhostip }}"
    gather_facts: true
    tasks:

      - debug:
          msg: "our inventnmame {{ playbookvminventoryname }}"

      - name: Ensure SSH warning banner is configured
        copy:
          dest: "/etc/issue.net"
          src: "files/issue.net"

      - name: add lines
        lineinfile:
         dest: /etc/ssh/sshd_config
         line: 'Banner /etc/issue.net'

      - name: restart sshd
        service:
          name: sshd
          state: restarted

      - name: list of commands for prepare tests
        file:
          state: directory
          path: /data
          owner: root
          group: root

      - name: just create a file
        shell: "touch /data/removeme"

      - name: create file with chattr +i
        shell: chattr +i /data/removeme
  
      - name: enable additional repo for docker
        shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

      - name: Install a list of packages
        yum:
          name: "{{ packages }}"
        vars:
          packages:
             - yum-utils
             - device-mapper-persistent-data
             - lvm2
             - docker-ce
             - docker-ce-cli
             - containerd.io

      - name: restart sshd
        service:
          name: docker
          state: restarted

      - name: send an email with results
        mail: 
          subject: "Postconfigurations has been done"
          to: "{{ adminemailnotifications }}"
          from: Li9 Demo <do-not-reply@demo.li9.com>
          body: 'Test-VM is redy for exam.'

      - name: send an email  to user that cloudformation is done
        mail:
          subject: "Your Li9 Exam system is ready"
          to: "{{ useremailnotifications }}"
          from: Li9 Exam <do-not-reply@li9.com>
          subtype: html
          body: "{{ lookup('template', 'files/mail.html.j2') }}"

#          body: |
#            Li9 Demo System has been successfully provisioned.
#            The following information is important to connect to the Test-Server:
#
#            *) Hosts is accessible via ssh
#            *) Test-Server IP is "{{ vmhostip }}"
#            *) SSH username: "{{ studentname }}"
#            *) SSH password: "{{ studentpwd }}"
#            *) ROOT access via "su -" with your password
#            *) Your system will be auto-destroyed in "{{ examtime }}" mins.
#
#            Thank you and good luck ....