- name:
  hosts: "{{ vmhostip }}"
  gather_facts: false

  vars:
    tasks_base_dir: "li9_exam_system/{{ testname }}/"
    exam_name: "Linux system administration exam"

  tasks:

    # Even not sure that we need to have 'when testname==linux'
    - name: Executing the only tasks specific for 'linux' exam module
      block:

      - name: Get tasks
        set_fact:
          exam_tasks: "{{ lookup('listtasks', tasks_base_dir) }}"

      - name: Save the tasks details for later using
        set_stats:
          data:
            exam_tasks: "{{ exam_tasks }}"

      - name: Debug selected tasks
        debug: var=exam_tasks

      - name: Execute selected tasks specific ansible-tasks
        include_tasks: "{{ exam_tasks.rootpath }}/{{ item.value.selected_task_path }}/pre_config.yml"
        with_dict: "{{ exam_tasks.topics }}"

      - name: Include additional task(s)
        include_tasks: "{{ item }}"
        loop:
          - included_tasks/common_bootstrap.yml
          - included_tasks/send_email.yml

      # end block section
      when: testname == "linux"

