---
- hosts: localhost
  gather_facts: false
  tasks:

      - shell: "whoami && w"

      - name: generate rondom name
        set_fact: rondomname="{{ 99999999999999999999999 | random | to_uuid }}"

      - name: import login-password from vault file
        include_vars:
          file: "files/api"

#      - debug:
#          msg: login = {{ apilogin }}
#      - debug:
#          msg: password = {{ apipassword }}
#      - debug:
#          msg: link = {{ apilink }}

      - name: just create a file
        template:
          dest: /var/www/cgi-bin/{{ rondomname }}
          owner: apache
          group: apache
          mode: '0755'
          src: "templates/cgi-bin.j2"

#      - debug:
#          msg: "useremailnotifications={{  useremailnotifications  }}"

#      - name: "save hyperlinkname for remove later"
#        set_stats:
#          data:
#            removehyperlinkfromtower: "{{ rondomname }}"

      - name: press to link for exam start
        mail:
          subject: "Li9 exam - Linux system administration"
          to: "{{ useremailnotifications }}"
#          from: Li9 Exam <do-not-reply@li9.com>
          from: "{{ adminemailnotifications }}"
          subtype: html
          body: "{{ lookup('template', 'templates/mailhyperlink.html.j2') }}"


      - name: just show hyperlink name
        debug:
          msg: "it is link to start ===> http://tower.demo.li9.com:8080/cgi-bin/{{ rondomname }}"

      - name: It is output informations to be sure regarding correct variables
        debug:
          msg: "useremailnotifications = {{ useremailnotifications }}"
