---
- hosts: localhost
  connection: local
  become_user: apache
  gather_facts: false
  become_method: su
  tasks:

      - name: generate rondom name
        command: "uuidgen"
        register: newuuidgen

      - name: create cgi-bin directory
        file:
          state: file
          path: /var/www/cgi-bin/"{{ newuuidgen.stdout }}"
