---
- hosts: localhost
  connection: local
  become_user: apache
  gather_facts: false
  become_method: su
  tasks:

      - name: generate rondom name
        set_fact: aaaa="{{ 9999999999999999 | random | to_uuid }}"

      - name: create cgi-bin directory
        file:
          state: file
          path: /var/www/cgi-bin/"{{ set_fact: aaaa="{{ 9999999999 | random | to_uuid }}" }}"
