---
- hosts: localhost
#  connection: local
#  become_user: apache
  gather_facts: false
#  become_method: su
  tasks:

      - shell: "whoami && w"

      - name: generate rondom name
        set_fact: rondomname="{{ 99999999999999999999999 | random | to_uuid }}"

      - name: just create a file
        template:
          dest: /var/www/cgi-bin/{{ rondomname }}
          owner: apache
          group: apache
          mode: '0755'
          src: "templates/sgi-bin.j2"

      - debug:
          msg: "useremailnotifications={{  useremailnotifications  }}"

      - name: "save hyperlinkname for remove later"
        set_stats:
          data:
            removehyperlinkfromtower: "{{ rondomname }}"

      - name: press to link for exam start
        mail:
          subject: "youre exam is ready"
          to: "{{ useremailnotifications }}"
          from: Li9 Demo <do-not-reply@demo.li9.com>
          body: |
            you have to press that link to exam start
            Your exam environment link will be auto-destroyed in "{{ timetolivehyperlink }}" mins.
            Your system will be auto-destroyed in "{{ examtime }}" mins after start (press link).
            Psease press link to start ===> http://tower.demo.li9.com:8080/cgi-bin/{{ rondomname }}