---
- hosts: localhost
#  connection: local
#  become_user: apache
  gather_facts: false
#  become_method: su
  tasks:
      - debug:
          msg: "rondname = {{ rondomname }}"

      - shell: "whoami && w"

      - name: generate rondom name
        set_fact: rondomname="{{ 99999999999999999999999 | random | to_uuid }}"

      - name: just create a file
        template:
          dest: /var/www/cgi-bin/{{ rondomname }}
          owner: apache
          group: apache
          mode: '0755'
          src: "templates/sgi-bin.j2"