---
- hosts: localhost
  gather_facts: false
  tasks:

      - name: just show hyperlink name
        debug:
          msg: "it is hyperlink name = {{ removehyperlinkfromtower }}"

      - name: sleep for "{{ timetolivehyperlink }}" seconds and remove hyperlink
        wait_for: 
          timeout: "{{ timetolivehyperlink }}"
          state: started
          msg: "sleeeeping :)"

      - shell: whoami

      - name: remove hyperlink of exam (it has been expired after "{{ timetolivehyperlink }}")
        file:
          path: /var/www/cgi-bin/{{ removehyperlinkfromtower }}
          state: absent
        ignore_errors: yes


      - name: remove hyperlink of exam (it has been expired after "{{ timetolivehyperlink }}")
        file:
          path: /var/www/cgi-bin/{{ removehyperlinkfromtower }}.old
          state: absent
          force: yes
        ignore_errors: yes