---
- hosts: localhost
  gather_facts: false
  tasks:

#      - name: It is output informations to be sure regarding correct variables
#        debug:
#          msg: "useremailnotifications = {{ useremailnotifications }}"

#      - debug: 
#          msg: "adminemailnotifications = {{ adminemailnotifications }}"

#      - debug:
#          msg: "adminemailnotifications = {{ adminemailnotifications }}"

#      - debug:
#          msg: "studentname = {{ studentname }}"

#      - debug:
#          msg: "studentpwd = {{ studentpwd }}"

#      - debug:
#          msg: "studentpwd = {{ instancetype }}"

#      - debug:
#          msg: "studentpwd = {{ examtime }}"

#      - name: just show hyperlink name
#        debug:
#          msg: "it is hyperlink name = {{ removehyperlinkfromtower }}"

      - name: sleep for "{{ timetolivehyperlink }}" seconds and remove hyperlink
        wait_for:
          timeout: "{{ timetolivehyperlink }}"
          state: started
          msg: "sleeeeping :)"

      - name: remove hyperlink of exam (it has been expired after "{{ timetolivehyperlink }}")
        file:
          path: /var/www/cgi-bin/{{ removehyperlinkfromtower }}
          state: absent
        ignore_errors: yes

      - name: remove hyperlink of exam (it has been expired after "{{ timetolivehyperlink }}")
        file:
          path: /var/www/cgi-bin/{{ removehyperlinkfromtower }}.old
          state: absent
          force: yes
        ignore_errors: yes
