---
- name:
  hosts: localhost
  connection: local
  tasks:

    - name: Set of tasks to execute when testname is defined
      when: testname is defined
      block:

      - name: sleep for "{{ exam_length_seconds }}" seconds and continue with play
        wait_for: timeout="{{ exam_length_seconds }}"
        delegate_to: localhost


      - name: Call wait Job
        include_tasks: "included_tasks/tower_client.yml"
        vars:
          job_template_name: "{{ job_templates.scoring.name }}"
          tower_action: "job_launch"
          tower_job_url: "{{ job_templates.scoring.endpoint }}"
          job_extra_vars:
            extra_vars:
              participant_id: "{{ participant_id | default('') }}"
              participant_details: "{{ participant_details | default('') }}"
              participant_email: "{{ participant_email | default(useremailnotifications) }}"
              initiator_email: "{{ initiator_email }}"
              useremailnotifications: "{{ useremailnotifications }}"
              testname: "{{ testname }}"
              stack_name: "{{ stack_name }}"
              student_name: "{{ student_name }}"
              exam_length_seconds: "{{ exam_length_seconds }}"
              vmhostip: "{{ vmhostip }}"
  
