---
- name: Delete user sshuser
  user:
    name: sshuser
    force: true
    remove: true
    state: absent


- name: Remove my private and public ssh keys
  file:
    path: "~/.ssh/{{ item }}"
    state: absent
  loop:
    - id_rsa
    - id_rsa.pub
    - known_hosts

