title: Create Dockerfile
description : |
  Create Dockerfile with requirements:
 
  * Dockerfile must be created in /home/student directory
  * Container must be built from the latest image of Apache Web-server
  * Containerized application must be exposed to the port 8081 on the host machine
  * Modify basic web-page of your webserver to contain string "This is a new welcome page!"
  * Build and run your container from Dockerfile. Container must be restarted after system reboot

explanation: |
  A participant should do following:
  * Create Dockerfile in /home/student directory with proper configuration
  * Dockerfile must be buildable
