title: Create Dockerfile
description : |
  Create Dockerfile with requirements:
 
  * Dockerfile must be created in /home/student directory
  * Container must be built from the latest image of Apache Web-server
  * Container must be exposed to the port 8081 (default 80)
  * Modify basic web-page of your webserver to contain string "This is a new welcome page!"
  * Build your container from Dockerfile, and start this container with a name "funky"

explanation: |
  A participant should do following:
  * Create Dockerfile in /home/student directory with proper configuration
  * Dockerfile must be buildable
